<?php

namespace Database\Seeders;

use App\Models\Blog;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class BlogSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $blogs = [
            ["user_id" => 1, "title" => "Bill Walsh leadership lessons","slug" => "bill_walsh_leadership_lessons_1","short_description" => "Like to know the secrets of transforming a 2-14 team into a 3x Super Bowl winning Dynasty?", "description" => "Structured gripped tape invisible moulded cups for sauppor firm hold strong powermesh front liner sport detail. Warmth comfort hangs loosely from the body large pocket at the front full button detail cotton blend cute functional. Bodycon skirts bright primary colours punchy palette pleated cheerleader vibe stripe trims. Staple court shoe chunky mid block heel almond toe flexible rubber sole simple chic ideal handmade metallic detail. Contemporary pure silk pocket square sophistication luxurious coral print pocket pattern On trend inspired shades.", "image" => "blog1.png"],
            ["user_id" => 1, "title" => "Bill Walsh leadership lessons","slug" => "bill_walsh_leadership_lessons_2", "short_description" => "Like to know the secrets of transforming a 2-14 team into a 3x Super Bowl winning Dynasty?", "description" => "Structured gripped tape invisible moulded cups for sauppor firm hold strong powermesh front liner sport detail. Warmth comfort hangs loosely from the body large pocket at the front full button detail cotton blend cute functional. Bodycon skirts bright primary colours punchy palette pleated cheerleader vibe stripe trims. Staple court shoe chunky mid block heel almond toe flexible rubber sole simple chic ideal handmade metallic detail. Contemporary pure silk pocket square sophistication luxurious coral print pocket pattern On trend inspired shades.", "image" => "blog2.png"],
            ["user_id" => 1, "title" => "Bill Walsh leadership lessons","slug" => "bill_walsh_leadership_lessons_3", "short_description" => "Like to know the secrets of transforming a 2-14 team into a 3x Super Bowl winning Dynasty?", "description" => "Structured gripped tape invisible moulded cups for sauppor firm hold strong powermesh front liner sport detail. Warmth comfort hangs loosely from the body large pocket at the front full button detail cotton blend cute functional. Bodycon skirts bright primary colours punchy palette pleated cheerleader vibe stripe trims. Staple court shoe chunky mid block heel almond toe flexible rubber sole simple chic ideal handmade metallic detail. Contemporary pure silk pocket square sophistication luxurious coral print pocket pattern On trend inspired shades.", "image" => "blog3.png"],
            ["user_id" => 1, "title" => "Bill Walsh leadership lessons","slug" => "bill_walsh_leadership_lessons_4", "short_description" => "Like to know the secrets of transforming a 2-14 team into a 3x Super Bowl winning Dynasty?", "description" => "Structured gripped tape invisible moulded cups for sauppor firm hold strong powermesh front liner sport detail. Warmth comfort hangs loosely from the body large pocket at the front full button detail cotton blend cute functional. Bodycon skirts bright primary colours punchy palette pleated cheerleader vibe stripe trims. Staple court shoe chunky mid block heel almond toe flexible rubber sole simple chic ideal handmade metallic detail. Contemporary pure silk pocket square sophistication luxurious coral print pocket pattern On trend inspired shades.", "image" => "blog4.png"],
            ["user_id" => 1, "title" => "Bill Walsh leadership lessons","slug" => "bill_walsh_leadership_lessons_5", "short_description" => "Like to know the secrets of transforming a 2-14 team into a 3x Super Bowl winning Dynasty?", "description" => "Structured gripped tape invisible moulded cups for sauppor firm hold strong powermesh front liner sport detail. Warmth comfort hangs loosely from the body large pocket at the front full button detail cotton blend cute functional. Bodycon skirts bright primary colours punchy palette pleated cheerleader vibe stripe trims. Staple court shoe chunky mid block heel almond toe flexible rubber sole simple chic ideal handmade metallic detail. Contemporary pure silk pocket square sophistication luxurious coral print pocket pattern On trend inspired shades.", "image" => "blog5.png"],
            ["user_id" => 1, "title" => "Bill Walsh leadership lessons","slug" => "bill_walsh_leadership_lessons_6", "short_description" => "Like to know the secrets of transforming a 2-14 team into a 3x Super Bowl winning Dynasty?", "description" => "Structured gripped tape invisible moulded cups for sauppor firm hold strong powermesh front liner sport detail. Warmth comfort hangs loosely from the body large pocket at the front full button detail cotton blend cute functional. Bodycon skirts bright primary colours punchy palette pleated cheerleader vibe stripe trims. Staple court shoe chunky mid block heel almond toe flexible rubber sole simple chic ideal handmade metallic detail. Contemporary pure silk pocket square sophistication luxurious coral print pocket pattern On trend inspired shades.", "image" => "blog6.png"],
            ["user_id" => 1, "title" => "Bill Walsh leadership lessons","slug" => "bill_walsh_leadership_lessons_7", "short_description" => "Like to know the secrets of transforming a 2-14 team into a 3x Super Bowl winning Dynasty?", "description" => "Structured gripped tape invisible moulded cups for sauppor firm hold strong powermesh front liner sport detail. Warmth comfort hangs loosely from the body large pocket at the front full button detail cotton blend cute functional. Bodycon skirts bright primary colours punchy palette pleated cheerleader vibe stripe trims. Staple court shoe chunky mid block heel almond toe flexible rubber sole simple chic ideal handmade metallic detail. Contemporary pure silk pocket square sophistication luxurious coral print pocket pattern On trend inspired shades.", "image" => "blog1.png"],
            ["user_id" => 1, "title" => "Bill Walsh leadership lessons","slug" => "bill_walsh_leadership_lessons_8", "short_description" => "Like to know the secrets of transforming a 2-14 team into a 3x Super Bowl winning Dynasty?", "description" => "Structured gripped tape invisible moulded cups for sauppor firm hold strong powermesh front liner sport detail. Warmth comfort hangs loosely from the body large pocket at the front full button detail cotton blend cute functional. Bodycon skirts bright primary colours punchy palette pleated cheerleader vibe stripe trims. Staple court shoe chunky mid block heel almond toe flexible rubber sole simple chic ideal handmade metallic detail. Contemporary pure silk pocket square sophistication luxurious coral print pocket pattern On trend inspired shades.", "image" => "blog2.png"],
            ["user_id" => 1, "title" => "Bill Walsh leadership lessons","slug" => "bill_walsh_leadership_lessons_9", "short_description" => "Like to know the secrets of transforming a 2-14 team into a 3x Super Bowl winning Dynasty?", "description" => "Structured gripped tape invisible moulded cups for sauppor firm hold strong powermesh front liner sport detail. Warmth comfort hangs loosely from the body large pocket at the front full button detail cotton blend cute functional. Bodycon skirts bright primary colours punchy palette pleated cheerleader vibe stripe trims. Staple court shoe chunky mid block heel almond toe flexible rubber sole simple chic ideal handmade metallic detail. Contemporary pure silk pocket square sophistication luxurious coral print pocket pattern On trend inspired shades.", "image" => "blog3.png"],
            ["user_id" => 1, "title" => "Bill Walsh leadership lessons","slug" => "bill_walsh_leadership_lessons_10", "short_description" => "Like to know the secrets of transforming a 2-14 team into a 3x Super Bowl winning Dynasty?", "description" => "Structured gripped tape invisible moulded cups for sauppor firm hold strong powermesh front liner sport detail. Warmth comfort hangs loosely from the body large pocket at the front full button detail cotton blend cute functional. Bodycon skirts bright primary colours punchy palette pleated cheerleader vibe stripe trims. Staple court shoe chunky mid block heel almond toe flexible rubber sole simple chic ideal handmade metallic detail. Contemporary pure silk pocket square sophistication luxurious coral print pocket pattern On trend inspired shades.", "image" => "blog4.png"],
            ["user_id" => 1, "title" => "Bill Walsh leadership lessons","slug" => "bill_walsh_leadership_lessons_11", "short_description" => "Like to know the secrets of transforming a 2-14 team into a 3x Super Bowl winning Dynasty?", "description" => "Structured gripped tape invisible moulded cups for sauppor firm hold strong powermesh front liner sport detail. Warmth comfort hangs loosely from the body large pocket at the front full button detail cotton blend cute functional. Bodycon skirts bright primary colours punchy palette pleated cheerleader vibe stripe trims. Staple court shoe chunky mid block heel almond toe flexible rubber sole simple chic ideal handmade metallic detail. Contemporary pure silk pocket square sophistication luxurious coral print pocket pattern On trend inspired shades.", "image" => "blog5.png"],
            ["user_id" => 1, "title" => "Bill Walsh leadership lessons","slug" => "bill_walsh_leadership_lessons_12", "short_description" => "Like to know the secrets of transforming a 2-14 team into a 3x Super Bowl winning Dynasty?", "description" => "Structured gripped tape invisible moulded cups for sauppor firm hold strong powermesh front liner sport detail. Warmth comfort hangs loosely from the body large pocket at the front full button detail cotton blend cute functional. Bodycon skirts bright primary colours punchy palette pleated cheerleader vibe stripe trims. Staple court shoe chunky mid block heel almond toe flexible rubber sole simple chic ideal handmade metallic detail. Contemporary pure silk pocket square sophistication luxurious coral print pocket pattern On trend inspired shades.", "image" => "blog6.png"],
        ];

        foreach($blogs as $blog){
            Blog::create($blog);
        }
    }
}
